spring:
  application:
    name: order
  datasource:
    url: jdbc:mysql://10.128.214.249:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  rabbitmq:
    host: 10.128.214.249
    username: guest
    password: guest
  redis:
    host: 10.128.214.249
    port: 6379
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
