spring:
  datasource:
    url: jdbc:mysql://10.128.245.59:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 10.128.245.59
    port: 6379
